### ISSUE TITLE
konga does not work

### ISSUE THREAD

**Issue by kopuskopecik** [d4rkstar/kong-konga-keycloak#10]
Hi
I wanna thank you for your amazing tutorial.

I apply all steps and took tokens, result but the konga container exited. I think postgresql version caused below log of konga's container:

Using postgres DB Adapter.
Database exists. Continue...
error: A hook (`orm`) failed to load!
/app/node_modules/sails-postgresql/lib/adapter.js:158
var collection = connectionObject.collections[table];
^

TypeError: Cannot read property 'collections' of undefined
at _DESCRIBE_ (/app/node_modules/sails-postgresql/lib/adapter.js:158:43)
at after (/app/node_modules/sails-postgresql/lib/adapter.js:1292:7)
at /app/node_modules/sails-postgresql/lib/adapter.js:1181:7
at /app/node_modules/sails-postgresql/node_modules/pg/lib/pool.js:84:11
at dispense (/app/node_modules/sails-postgresql/node_modules/pg/node_modules/generic-pool/lib/generic-pool.js:250:16)
at Object.me.release (/app/node_modules/sails-postgresql/node_modules/pg/node_modules/generic-pool/lib/generic-pool.js:349:5)
at /app/node_modules/sails-postgresql/node_modules/pg/lib/pool.js:88:20
at /app/node_modules/sails-postgresql/lib/adapter.js:1295:9
at Query.callback (/app/node_modules/sails-postgresql/lib/adapter.js:195:26)
at Query.handleError (/app/node_modules/sails-postgresql/node_modules/pg/lib/query.js:106:17)
at Connection.<anonymous> (/app/node_modules/sails-postgresql/node_modules/pg/lib/client.js:171:26)
at Connection.emit (events.js:310:20)
at Connection.EventEmitter.emit (domain.js:482:12)
at Socket.<anonymous> (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:109:12)
at Socket.emit (events.js:310:20)
at Socket.EventEmitter.emit (domain.js:482:12)
at addChunk (_stream_readable.js:286:12)
at readableAddChunk (_stream_readable.js:268:9)
at Socket.Readable.push (_stream_readable.js:209:10)
at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
Using postgres DB Adapter.
Database exists. Continue...
error: A hook (`orm`) failed to load!
/app/node_modules/sails-postgresql/lib/adapter.js:158
var collection = connectionObject.collections[table];
^

TypeError: Cannot read property 'collections' of undefined
at _DESCRIBE_ (/app/node_modules/sails-postgresql/lib/adapter.js:158:43)
at after (/app/node_modules/sails-postgresql/lib/adapter.js:1292:7)
at /app/node_modules/sails-postgresql/lib/adapter.js:1181:7
at /app/node_modules/sails-postgresql/node_modules/pg/lib/pool.js:84:11
at /app/node_modules/sails-postgresql/node_modules/pg/node_modules/generic-pool/lib/generic-pool.js:281:11
at /app/node_modules/sails-postgresql/node_modules/pg/lib/pool.js:58:20
at Connection.<anonymous> (/app/node_modules/sails-postgresql/node_modules/pg/lib/client.js:149:7)
at Object.onceWrapper (events.js:417:26)
at Connection.emit (events.js:322:22)
at Connection.EventEmitter.emit (domain.js:482:12)
at Socket.<anonymous> (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:109:12)
at Socket.emit (events.js:310:20)
at Socket.EventEmitter.emit (domain.js:482:12)
at addChunk (_stream_readable.js:286:12)
at readableAddChunk (_stream_readable.js:268:9)
at Socket.Readable.push (_stream_readable.js:209:10)
at TCP.onStreamRead (internal/stream_base_commons.js:186:23)

**Comment by d4rkstar** [comment]
Hello,
it seems that your problem is related to postgres' version.

Take a look here: https://github.com/pantsel/konga/issues/462

Konga only run on postgresql 11 :(

Let me know !
